# Generated by Django 4.1.7 on 2023-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="startedjob",
            name="notes",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
