# Generated by Django 4.1.7 on 2023-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startedjob",
            name="client_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
