# Generated by Django 4.1.7 on 2023-04-02 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedJobItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklist.completedjob",
                    ),
                ),
                (
                    "job_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklist.jobitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
