# Generated by Django 4.1.7 on 2023-04-02 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0002_completedjobitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completedjob",
            old_name="completed",
            new_name="check_list_completed",
        ),
    ]
