# Generated by Django 4.1.7 on 2023-04-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0003_alter_startedjob_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedjob",
            name="check_list_completed",
            field=models.BooleanField(default=False),
        ),
    ]
