# Generated by Django 4.1.7 on 2023-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0003_client_remove_startedjob_client_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
